blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: 'âœ¨ issue-form'
    description: 'Repoì— ì´ìŠˆë¥¼ ìƒì„±í•˜ë©°, ìƒì„±ëœ ì´ìŠˆëŠ” Jiraì™€ ì—°ë™ë©ë‹ˆë‹¤.'
    file: ISSUE_TEMPLATE/issue-form.yml
  - name: 'ğŸ› fix-template'
    description: 'ë²„ê·¸ ë°œìƒ ì‹œ ì‚¬ìš©í•´ì£¼ì„¸ìš”'
    file: ISSUE_TEMPLATE/fix-form.yml
